# -*- sh -*-

## pipのダウンロードキャッシュ
export PIP_DOWNLOAD_CACHE=${HOME}/.pip_cache
## パッケージをvirtualenvにインストール
export PIP_RESPECT_VIRTUALENV=true
## pipの実行にvirtualenvを必須にする
export PIP_REQUIRE_VIRTUALENV=true
## 仮想環境を置くディレクトリ
export WORKON_HOME=${HOME}/.virtualenvs
## virtualenvwrapperスクリプトの実行
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

# ページャの設定
if type lv > /dev/null 2>&1; then
    ## lvを優先する。
    export PAGER="lv"
else
    ## lvがなかったらlessを使う。
    export PAGER="less"
fi

# lvの設定
if [ "$PAGER" = "lv" ]; then
    ## -c: ANSIエスケープシーケンスの色付けなどを有効にする。
    ## -l: 1行が長くと折り返されていても1行として扱う。
    ##     （コピーしたときに余計な改行を入れない。）
    export LV="-c -l"
else
    ## lvがなくてもlvでページャーを起動する。
    alias lv="$PAGER"
fi

# エディタの設定
## vimを使う。
export EDITOR=vim
## vimがなくてもvimでviを起動する。
if ! type vim > /dev/null 2>&1; then
    alias vim=vi
fi
