# -*- sh -*-

## sudoユーザーに環境変数を引き継ぐ
alias sudo='sudo env PATH=$PATH'
## pipのダウンロードキャッシュ
export PIP_DOWNLOAD_CACHE=${HOME}/.pip_cache

# ページャの設定
if type lv > /dev/null 2>&1; then
    ## lvを優先する。
    export PAGER="lv"
else
    ## lvがなかったらlessを使う。
    export PAGER="less"
fi

# lvの設定
if [ "$PAGER" = "lv" ]; then
    ## -c: ANSIエスケープシーケンスの色付けなどを有効にする。
    ## -l: 1行が長くと折り返されていても1行として扱う。
    ##     （コピーしたときに余計な改行を入れない。）
    export LV="-c -l"
else
    ## lvがなくてもlvでページャーを起動する。
    alias lv="$PAGER"
fi

# エディタの設定
export EDITOR=vim

# リダイレクトをセキュアに実行
set -o noclobber

# haskell cabalコマンドでインストールした実行ファイル群へパスを通す
export PATH="${HOME}/.cabal/bin:$PATH"

# anyenv
# git clone https://github.com/riywo/anyenv ~/.anyenv
export PATH="${HOME}/.anyenv/bin:${PATH}"
eval "$(anyenv init -)"
## for nodejs packages installed locally
export PATH=$PATH:./node_modules/.bin
