" to install neobundle.vim, execute following one liner
" git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
" ----- start NeoBundle settings -----
set nocompatible
filetype off

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim
  call neobundle#rc(expand('~/.vim/bundle'))
endif

NeoBundle 'Shougo/neocomplcache.vim'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'mhinz/vim-startify'

filetype plugin on
filetype indent on


" ----- common settings -----
" エンコード
set encoding=utf8
" ファイルエンコード
set fileencoding=utf-8
" シンタックスハイライト
syntax on
" 256色表示
set t_Co=256
" ステータスバーを常に表示
set laststatus=2
"set statusline=%{expand('%:p:t')}\ %<[%{expand('%:p:h')}]%=\ %m%r%y%w[%{&fenc!=''?&fenc:&enc}][%{&ff}][%3l,%3c,%3p]
" カーソル行をアンダーライン
set cursorline
" 行番号を表示
set number
" 変更中のファイルでも、保存しないで他のファイルを表示
set hidden
" 新しく開く代わりにすでに開いてあるバッファを開く
set switchbuf=useopen
" 小文字の検索でも大文字も見つかるようにする
set ignorecase
" ただし大文字も含めた検索の場合はその通りに検索する
set smartcase
" インクリメンタルサーチを行う
set incsearch
" 検索結果をハイライト
set hlsearch
" 不可視文字を表示
set list
set listchars=trail:-,extends:>,precedes:<,nbsp:%,eol:$,tab:▸\ 
" タブ幅を指定
set tabstop=4
set shiftwidth=4
" タブを半角スペースに変換
set expandtab
" 対応括弧をハイライト表示する
set showmatch
" 対応括弧の表示秒数を3秒にする
set matchtime=3
" インサートモード時にバックスペースを使う
set backspace=indent,eol,start
" 選択した範囲のインデントサイズを連続変更
vnoremap < <gv
vnoremap > >gv


" ----- key-bind settings -----
" ESCを2回入力で検索時のハイライトを解除
nnoremap <ESC><ESC> :nohlsearch<CR>


" ----- NERDTree settings -----
let file_name = expand("%")
nnoremap <C-e> :NERDTreeToggle<CR>
" vim起動時にツリーを表示する
"if has('vim_starting') &&  file_name == ""
"	autocmd VimEnter * NERDTree ./
"endif


" ----- lightline settings -----
let g:lightline = {
    \ 'colorscheme': 'solarized'
    \ }


" ----- Neocomplcache settings -----
" Neocomplcacheの有効化
let g:neocomplcache_enable_at_startup = 1
" 入力に大文字が入力されていたら、大文字小文字の区別をする
let g:neocomplcache_enable_smart_case = 0
" アンダーバー区切りの補完を無効化(有効にすると重い)
let g:neocomplcache_enable_underbar_completion = 0
" 大文字小文字区切りの曖昧検索を無効化(有効にすると重い)
let g:neocomplcache_enable_camel_case_completion = 0
" キャッシュする最小文字列長
let g:neocomplcache_min_syntax_length = 4


" ----- startify settings -----
" startifyのヘッダー部分に表示する文字列を設定する(dateコマンドを実行して日付を設定している)
let g:startify_custom_header = map(split(system('date'), '\n'), '"   ". v:val') + ['','']
" デフォルトだと、最近使ったファイルの先頭は数字なので、使用するアルファベットを指定
let g:startify_custom_indices = ['f', 'g', 'h', 'r', 'i', 'o', 'b']
"よく使うファイルをブックマークとして登録しておく
let g:startify_bookmarks = [
        \ '~/dotfiles/vim.d/vimrc',
        \ '~/.subversion/config',
        \ '~/.gitconfig',
        \ ]


" ----- window operation settings -----
" Ctrl + hjkl でウィンドウ間を移動
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
" Shift + 矢印でウィンドウサイズを変更
nnoremap <S-Left>  <C-w><<CR>
nnoremap <S-Right> <C-w>><CR>
nnoremap <S-Up>    <C-w>-<CR>
nnoremap <S-Down>  <C-w>+<CR>


" ----- key bind settings -----
" インサートモードのキーバインド
inoremap <c-a> <home>
inoremap <c-e> <end>
inoremap <c-j> <down>
inoremap <c-k> <up>
inoremap <c-h> <left>
inoremap <c-l> <right>
inoremap <silent> <C-f> <S-Right>
inoremap <silent> <C-b> <S-Left>
inoremap <silent> <c-d> <c-g>u<Del>
inoremap <silent> <c-g> <c-g>u<BS>
inoremap <silent> <Tab> <c-g>u<c-t>
inoremap <silent> <S-Tab> <c-g>u<c-d>
